# Generated by Django 2.2 on 2019-05-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_word_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SavedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_word_text', models.CharField(max_length=200)),
            ],
        ),
    ]
