# Generated by Django 2.2 on 2019-05-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_currentword_savedword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentword',
            old_name='current_word_text',
            new_name='current_word',
        ),
    ]
