# Generated by Django 2.2 on 2019-05-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190514_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentword',
            old_name='current_word',
            new_name='current_word_text',
        ),
    ]
