# Generated by Django 2.2 on 2019-05-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190515_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score_text', models.IntegerField()),
            ],
        ),
    ]
